[settings]
name = "Kickoff Only"
agent_id = "virxec/kickoff-only"
run_command = "./kickoff_only.py"
run_command_linux = "./venv/bin/python kickoff_only.py"

[details]
developer = "VirxEC"
description = "A few seconds after kickoff ends, this puts the ball in the net of the kickoff loser. Requires state setting."
fun_fact = 'You might want to enable "Skip Replays" under Extra and "Unlimited" Match Length under Mutators.'
github = "https://github.com/VirxEC/KickoffOnly"
language = "Python"
